### PR TITLE
Allow to save vocab with non-consecutive indices

### LINKED ISSUE #53: Allow empty line in the vocab file
`BertSudachipyTokenizer.save_vocabulary` fails when vocab file contains empty line (or duplicated vocab):

https://github.com/WorksApplications/SudachiTra/blob/7ff005f3846848470ec89dcc8ba12c31c2d394a9/sudachitra/tokenization_bert_sudachipy.py#L93-L94

Want to save (reproduce) vocab file in those cases.

### PR DESCRIPTION
**Pull request by mh-northlander**
Fix #53.

In the case indices are not consecutive, just write an empty line.

### CODE REVIEW

**Review by eiennohito — APPROVED** [review]
LGTM, but I do not understand the problem

**Comment by mh-northlander** [comment]
The vocab file of chiTra-1.1 does have an empty line.

**Comment by katsutan** [comment]
During the current operation, was there an error caused by this?

**Comment by mh-northlander** [comment]
Loading and using the tokenizer has no problem (i.e. finetuning or evaluation).

But sometimes we want to save model together with the tokenizer, and this causes problem at that time.
ex: https://github.com/huggingface/transformers/blob/3ec8171bedff6139a23dff192b9e8af33c1fca9a/examples/pytorch/text-classification/run_glue.py#L541

**Review by katsutan — APPROVED** [review]
Please write the current problem in Issue.

**Pull request merged**
