### PR TITLE
Support 接尾辞-動詞的 and 接尾辞-形容詞的

### PR DESCRIPTION
**Pull request by KoichiYasuoka**
Tentative support for "強がっているが怖がりなのだ", please see detail in [my diary](https://srad.jp/~yasuoka/journal/653055/) written in Japanese.

### CODE REVIEW

**Comment by katsutan** [comment]
Thank you for reporting chiTra.

This conjugation normalization is not what we expect and we would like to fix it.
However, the tokenizer used for the pre-trained model must be retained.
Therefore, it needs to be rebuilt with the new options.

**Comment by KoichiYasuoka** [comment]
I'm vague what kinds of "new options" are suitable for `BertSudachipyTokenizer`...

**Comment by katsutan** [comment]
Sorry for the lack of explanation.

To summarize the current issue, "NORMALIZED_AND_SURFACE" using "conjugation_matcher" is set to be used in the currently released pre-trained model, so we would like to avoid changing this behavior.

The solution is to add a new Enum to WordFormTypes and add a separate process to word_formatters.
Also, the pos_matcherh called at that must be generated as a separate item from the conjugation_matcher.

**Comment by mh-northlander** [comment]
This seems same to the word_form_type implemented in #50.

Check:
```python
import sudachipy
dic = sudachipy.Dictionary()
pm1 = dic.pos_matcher(lambda p: p[5] == "*")
pm2 = dic.pos_matcher(lambda p: p[0] in chitra.word_formatter.CONJUGATIVE_POS or p[0] == '接尾辞' and p[1] in {'動詞的', '形容詞的'})
set(pm1) == set(~pm2)  # returns True
```

**Pull request closed without merging**
